services:
  node-smoke:
    build:
      context: ..
      dockerfile: smoke/node/Dockerfile
  bun-smoke:
    build:
      context: ..
      dockerfile: smoke/bun/Dockerfile
  browser-smoke:
    build:
      context: ..
      dockerfile: smoke/browser/Dockerfile
